paths:
  output_dir: outputs

data:
  use_kagglehub: true
  kaggle_dataset: "shakthisairam123/gym-workout-imu-dataset"
  window_size: 300
  step_size: 150
  smooth_kernel: 5
  downsample_factor: 2
  downsample_mode: "avg"
  train_split: 0.8

training:
  device: "auto"           # "cuda", "cpu", or "auto"
  batch_size: 32
  epochs: 5
  learning_rate: 0.0001
  grad_clip: 1.0
  num_workers: 2

model:
  hidden_dim: 64
  lstm_layers: 1
